image: java:8-jdk

stages:
  - build
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  coverage: '/Total.*?(\d+)%/'
  script:
    - ./gradlew check --info -PexcludeTests=**/RastreioTest.class
    - ./gradlew jacocoTestReport
    - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'

staging:
  stage: test
  script:
    - ./gradlew check --info -PincludeTests=**/RastreioTest.class
  allow_failure: true

publish:
  stage: publish
  script:
    - ./gradlew publishToMavenLocal
